[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

[workspace.dependencies]
gc_disc = { path = "crates/gc_disc" }
prg = { path = "crates/prg" }
ngc_texture = { path = "crates/ngc_texture" }
ngc_model = { path = "crates/ngc_model" }
ngc_collision = { path = "crates/ngc_collision" }
qb = { path = "crates/qb" }
ngc_anim = { path = "crates/ngc_anim" }
skate = { path = "crates/skate" }
anyhow = "1"
clap = { version = "4", features = ["derive"] }
thiserror = "2"
